Algoritmo "ConteAte10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/9/2021
Var
// Seção de Declarações das variáveis 
  contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 0
   Enquanto (contador <= 10) faca
   Escreval (contador)
   contador <- contador + 1
   FimEnquanto

Fimalgoritmo