Algoritmo "creuzal03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/8/2021
Var
// Seção de Declarações das variáveis 
      F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreval("Qual a temperatura aqui?")
    Leia (F)
    C <- (f-32) / 1.8
    Escreval("No Brasil estaria :", C:4:1)

Fimalgoritmo