Algoritmo "creuzal01"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/8/2021
Var

    ano_atual:Inteiro
     ano_nasc:Inteiro
     idade: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Em que ano nos estamos")
   Leia(ano_atual)
   Escreval("Em que ano eu nasci")
   Leia(ano_nasc)
   idade <- ano_atual-ano_nasc
   Escreval("Minha idade sera;",idade)

Fimalgoritmo