Algoritmo "meunome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/8/2021
Var
// Seção de Declarações das variáveis 
  Nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        Escreval ("Digite o Nome")
        Leia (Nome)
        Escreval("Mouito prazer te conhecer:",Nome)

Fimalgoritmo