Algoritmo "parOUImpar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/8/2021
Var
// Seção de Declarações das variáveis 
    N: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("digite um numero qualquer")
   Leia (N)
   Se (N % 2 = 0) entao
        Escreval(" o numero", N," é PAR")
   senao
        Escreval(" o numero", N," é IMPAR")
   FimSe

Fimalgoritmo