Algoritmo "Antecessor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/8/2021
Var
// Seção de Declarações das variáveis 
valor:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("boa noite")
  Escreval(" Digite um valor")
  Leia (valor)
  antecessor <- valor-1
  Escreval(" o valor antecessor digitado é :", antecessor )

Fimalgoritmo