Algoritmo "sucessor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/8/2021
Var
// Seção de Declarações das variáveis 
   numero:inteiro
   sucessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval ("Digite um numero")
  Leia(numero)
  sucessor <- numero+1
  Escreval(" o sucessor digitado é :", sucessor)

Fimalgoritmo