Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/10/2021
Var
    i : inteiro

Inicio

     escreva ("Os números pares são:" )
     para i de 1 ate 500 faca
     se ((i mod 2) = 0) entao
     se (i <> 500) entao
     escreva(i, ",")
     senao
     escreva (i)
     fimse
     fimse
     fimpara

Fimalgoritmo