Algoritmo "listarepita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/11/2021
Var
// Seção de Declarações das variáveis
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont<-15
repita
Escreval(cont, " * ", cont, " = ",cont*cont)
cont<-cont+1
ate cont>200


Fimalgoritmo